language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - OCULAR_ENV='5.4'

install:
  - curl http://get.sensiolabs.org/security-checker.phar -o security-checker.phar

script:
  - php -n security-checker.phar security:check --format=simple
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=build/logs/coverage.clover
  - if [ $(phpenv version-name) = $OCULAR_ENV ]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover; fi
